import { CLUBS } from '../core/contracts/cockpit';
import { icon } from './icons';

export const cockpitMarkup = `
<main class="cockpit-shell">
 <header class="app-header"><button id="controllerBack" class="icon-button" aria-label="Back or controller menu">${icon('back')}</button><div class="controller-brand">purity<span> / PLAY</span></div><button id="openSettings" class="icon-button" aria-label="Course settings">${icon('settings')}</button></header>
 <div class="connection-row"><span id="connection" role="status">Connecting…</span><span class="live-dot">LOCAL PLAY</span></div>
 <fieldset id="controls" disabled>
  <div data-control-panel="shot">
   <section class="shot-heading"><p class="eyebrow">CREEK & SHOULDER · 01</p><h1 id="phaseTitle">Your next shot.</h1><p id="phaseHint">Set your line, then make your move.</p></section>
   <div class="shot-ticket"><div class="readings"><div class="distance-reading"><span id="distance">—</span><small>YARDS TO AIM</small></div><div><span id="shot">1</span><small>SHOT</small></div><div><span id="lie">—</span><small>LIE</small></div></div><div class="weather"><span id="wind">Reading wind…</span><progress id="windBar" max="1" value="0" aria-label="Wind strength"></progress></div></div>
   <section class="control-card aim-card"><div class="card-heading"><h2>Your line</h2><div class="segmented"><button id="aimMode" aria-pressed="true">Aim</button><button id="inspectMode" aria-pressed="false">Read ground</button></div></div><div id="touchpad" role="group" tabindex="0" aria-label="Drag or use arrow keys to move the aim point" aria-describedby="padHelp"><div class="pad-target" aria-hidden="true"><i></i></div><span id="padTitle">Move your aim</span><small id="padHelp">Drag here. Follow the marker on the course.</small></div><div class="aim-tools"><div class="nudges"><button data-dx="-1" data-dy="0" aria-label="Move left">←</button><button data-dx="0" data-dy="1" aria-label="Move up">↑</button><button data-dx="0" data-dy="-1" aria-label="Move down">↓</button><button data-dx="1" data-dy="0" aria-label="Move right">→</button></div><label class="fine"><input id="fine" type="checkbox" role="switch"> Fine aim</label></div><p id="terrain" class="terrain" hidden></p></section>
   <section class="control-card shot-card"><button id="chooseClub" class="club-summary"><span><small>IN YOUR HAND</small><strong id="clubName">Driver</strong></span><span class="club-glyph" aria-hidden="true">${icon('club')}</span><span>Change ›</span></button><label class="slider-label" for="effort">Effort <output id="effortValue">100%</output></label><input id="effort" type="range" min="15" max="110" step="0.5" value="100"><div class="range-ends"><span>Easy</span><span>Full swing</span></div><details class="shot-tuning"><summary>Shape & flight <span id="tuningSummary">Straight · stock height</span></summary><label class="slider-label" for="shape">Curve <output id="shapeValue">Straight</output></label><input id="shape" type="range" min="-100" max="100" value="0"><div class="range-ends"><span>Fade</span><span>Draw</span></div><label class="slider-label" for="height">Height <output id="heightValue">Stock</output></label><input id="height" type="range" min="-100" max="100" value="0"></details></section>
   <section id="resultCard" class="result-card" hidden><p class="eyebrow">SHOT COMPLETE</p><h2>A moment to regroup.</h2><p id="result" role="status"></p><button id="mulligan" class="secondary">Take a mulligan ↺</button></section>
  </div>
  <section data-control-panel="bag" hidden><p class="eyebrow">YOUR EQUIPMENT</p><h1>The right club.<br>The right shot.</h1><p class="panel-intro">Choose a club, then return to your shot to set effort and flight.</p><div class="bag-illustration" aria-hidden="true"><i></i><i></i><i></i><span>09<br><small>CLUBS</small></span></div><label class="club-picker" for="club">Select your club<select id="club">${CLUBS.map((c) => `<option value="${c}">${({ D: 'Driver', PUTT: 'Putter', CHIP: 'Chip', '3W': '3 wood' } as Record<string, string>)[c] || c.replace('I', ' iron').replace('PW', 'Pitching wedge').replace('SW', 'Sand wedge')}</option>`).join('')}</select></label><p class="panel-intro">Woods for distance. Irons for approach. Wedges and putter for the finishing touches.</p><button id="backToShot" class="primary">Back to my shot →</button></section>
  <section data-control-panel="round" hidden><p class="eyebrow">PRACTICE ROUND</p><h1>Creek &<br>Shoulder.</h1><p class="panel-intro">One hole. Plenty of possibilities. Shape your approach around the creek and finish on the raised green.</p><div class="round-summary"><span>01 <small>HOLE</small></span><span id="roundShot">1</span><small>CURRENT SHOT</small><p id="roundStatus">Ready to play</p></div><h2>Explore the course</h2><div class="views"><button data-view="hole">Whole hole ↗</button><button data-view="ball">Your ball ◎</button><button data-view="green">Green ⚑</button></div><button id="roundSettings" class="secondary">Conditions & appearance →</button><p class="panel-intro">This is practice play. Mulligans are available after a shot; changing conditions starts a fresh hole.</p></section>
  <div class="play-dock"><div class="dock-caption"><span id="dockHint">Ready when you are.</span><span>●</span></div><button id="play" class="primary">Play this shot</button><p id="notice" role="alert"></p></div>
 </fieldset>
 <nav class="controller-nav" aria-label="Controller navigation"><button data-panel="shot" aria-pressed="true"><span>${icon('shot')}</span>Shot</button><button data-panel="bag" aria-pressed="false"><span>${icon('bag')}</span>My bag</button><button data-panel="round" aria-pressed="false"><span>${icon('flag')}</span>Round</button></nav>
</main>
<dialog id="courseSettings" class="settings-sheet" aria-labelledby="settingsTitle"><header class="sheet-heading"><div><p class="eyebrow">YOUR EXPERIENCE</p><h2 id="settingsTitle">Settings</h2></div><button id="closeSettings" class="icon-button" aria-label="Close settings">×</button></header><label>Interface<select id="theme"><option value="dark">Forest · dark</option><option value="light">Ivory · light</option></select></label><fieldset id="settingsControls" disabled><h3>Course conditions</h3><p class="settings-note">Applying conditions starts a new practice hole.</p><div class="settings-grid"><label>Tee<select id="tee"><option value="red">Forward</option><option value="white" selected>Middle</option><option value="blue">Back</option></select></label><label>Pin<select id="pin"><option value="easy">Easy</option><option value="moderate" selected>Moderate</option><option value="challenging">Challenging</option></select></label><label>Wind<select id="windChoice"><option value="calm">Calm</option><option value="light">Light</option><option value="moderate" selected>Moderate</option><option value="strong">Strong</option></select></label><label>Direction (degrees)<input id="towardDeg" type="number" min="0" max="359" value="0"></label></div><label>Ground<select id="moisture"><option value="dry">Dry & firm</option><option value="moderate" selected>Moderate</option><option value="wet">Wet & soft</option></select></label><button id="applySetup" class="secondary">Apply & start a new hole</button><label>Course appearance<select id="renderer"><option value="procedural">Illustrated course</option><option value="photo">Original photographic study</option></select></label><button id="reset" class="text-button">Restart this hole</button><details class="diagnostics"><summary>Connection details</summary><p id="latency">Connected locally.</p></details></fieldset></dialog>
<dialog id="controllerMenu" class="settings-sheet"><header class="sheet-heading"><h2>Your controller</h2><button id="closeControllerMenu" class="icon-button" aria-label="Back to controller">×</button></header><p class="panel-intro">Your round stays on the display. You can return here with the same pairing link.</p><a class="secondary" href="/">Leave controller & go home ↗</a></dialog>`;
