import { CLUBS } from '../core/contracts/cockpit';

export const cockpitMarkup = `
<main class="cockpit-shell">
  <header class="app-header"><a class="wordmark" href="#" aria-label="Purity golf">purity<span>↗</span></a><button id="openSettings" class="icon-button" type="button" aria-label="Course settings"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 17h16M8 4v6m8 4v6"/></svg></button></header>
  <div class="connection-row"><span id="connection" role="status">Connecting to your course…</span><span class="hole-label">HOLE 01 · PAR 4</span></div>
  <section class="shot-heading"><p class="eyebrow">CREEK & SHOULDER</p><h1 id="phaseTitle">Make it yours.</h1><p id="phaseHint">Pick your line. Choose your club. Take your shot.</p></section>
  <div class="readings"><div class="distance-reading"><span id="distance">—</span><small>yd to your aim</small></div><div><span id="shot">1</span><small>shot</small></div><div><span id="lie">—</span><small>your lie</small></div></div>
  <div class="weather"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 8h12a3 3 0 1 0-3-3M3 12h16a2 2 0 1 1-2 2M3 16h7a2 2 0 1 1-2 2"/></svg><span id="wind">Reading the wind…</span><progress id="windBar" max="1" value="0" aria-label="Wind strength"></progress></div>
  <fieldset id="controls" disabled>
    <section class="control-card aim-card" aria-labelledby="aimTitle">
      <div class="card-heading"><div><span class="step">01</span><h2 id="aimTitle">Find your line</h2></div><div class="segmented"><button type="button" id="aimMode" aria-pressed="true">Aim</button><button type="button" id="inspectMode" aria-pressed="false">Read green</button></div></div>
      <div id="touchpad" role="group" tabindex="0" aria-label="Drag or use arrow keys to move the aim point" aria-describedby="padHelp"><div class="pad-target" aria-hidden="true"><i></i><b></b></div><span id="padTitle">Drag here. Watch the course.</span><small id="padHelp">Your aim moves with your finger.</small></div>
      <div class="aim-tools"><div class="nudges" aria-label="Move target"><button type="button" data-dx="-1" data-dy="0" aria-label="Move left">←</button><button type="button" data-dx="0" data-dy="1" aria-label="Move up">↑</button><button type="button" data-dx="0" data-dy="-1" aria-label="Move down">↓</button><button type="button" data-dx="1" data-dy="0" aria-label="Move right">→</button></div><label class="fine"><input id="fine" type="checkbox" role="switch"><span>Fine aim</span></label></div>
      <p id="terrain" class="terrain" hidden>Move the pad to inspect the ground.</p>
    </section>
    <section class="control-card shot-card" aria-labelledby="shotTitle"><div class="card-heading"><div><span class="step">02</span><h2 id="shotTitle">Shape your shot</h2></div></div>
      <label class="club-picker" for="club"><span><small>YOUR CLUB</small><strong id="clubName">Driver</strong></span><select id="club" aria-label="Club">${CLUBS.map((c) => `<option value="${c}">${({ D: 'Driver', PUTT: 'Putter', CHIP: 'Chip', '3W': '3 wood' } as Record<string, string>)[c] || c.replace('I', ' iron').replace('PW', 'Pitching wedge').replace('SW', 'Sand wedge')}</option>`).join('')}</select><span class="club-chevron" aria-hidden="true">⌄</span></label>
      <label class="slider-label" for="effort">Effort <output id="effortValue">100%</output></label><input id="effort" type="range" min="15" max="110" step="0.5" value="100"><div class="range-ends"><span>Easy</span><span>Full swing</span></div>
      <details class="shot-tuning"><summary>Shape & flight <span id="tuningSummary">Straight · stock height</span></summary><div class="tuning-body"><label class="slider-label" for="shape">Curve <output id="shapeValue">Straight</output></label><input id="shape" type="range" min="-100" max="100" value="0"><div class="range-ends"><span>Fade →</span><span>← Draw</span></div><label class="slider-label" for="height">Height <output id="heightValue">Stock</output></label><input id="height" type="range" min="-100" max="100" value="0"><div class="range-ends"><span>Low</span><span>High</span></div></div></details>
    </section>
    <section id="resultCard" class="result-card" hidden aria-label="Shot result"><p class="eyebrow">YOUR SHOT</p><p id="result" role="status"></p><button type="button" id="mulligan" class="text-button">Take a mulligan ↺</button></section>
    <div class="views" aria-label="Display camera"><button type="button" data-view="hole">↗ Whole hole</button><button type="button" data-view="ball">◎ Ball</button><button type="button" data-view="green">⚑ Green</button></div>
    <div class="play-dock"><div class="dock-caption"><span id="dockHint">Your line. Your call.</span><span class="dock-step">03 · PLAY</span></div><button type="button" id="play" class="primary">Play this shot</button><p id="notice" role="alert"></p></div>
  </fieldset>
</main>
<dialog id="courseSettings" class="settings-sheet" aria-labelledby="settingsTitle"><div class="sheet-handle" aria-hidden="true"></div><div class="sheet-heading"><div><p class="eyebrow">MAKE YOURSELF AT HOME</p><h2 id="settingsTitle">Course settings</h2></div><button type="button" id="closeSettings" class="icon-button" aria-label="Close settings">×</button></div><fieldset id="settingsControls" disabled>
  <p class="settings-note">Changing conditions starts a new practice hole.</p><div class="settings-grid"><label>Tee<select id="tee"><option value="red">Red · forward</option><option value="white" selected>White · middle</option><option value="blue">Blue · back</option></select></label><label>Pin<select id="pin"><option value="easy">Easy</option><option value="moderate" selected>Moderate</option><option value="challenging">Challenging</option></select></label><label>Wind<select id="windChoice"><option value="calm">Calm</option><option value="light">Light</option><option value="moderate" selected>Moderate</option><option value="strong">Strong</option></select></label><label>Blowing toward<input id="towardDeg" type="number" min="0" max="359" value="0" aria-label="Wind direction in degrees"></label></div>
  <label>Ground<select id="moisture"><option value="dry">Dry & firm</option><option value="moderate" selected>Moderate</option><option value="wet">Wet & soft</option></select></label><button type="button" id="applySetup" class="secondary">Apply & start a new hole</button>
  <div class="settings-divider"></div><label>Course appearance<select id="renderer"><option value="procedural">Living course · procedural</option><option value="photo">Photographic reference</option></select></label><p class="settings-note">On the display: drag to explore, scroll to zoom, double-click to reframe. Shots follow automatically.</p><button type="button" id="reset" class="text-button">Restart this hole</button><details class="diagnostics"><summary>Connection details</summary><p id="latency">Connected locally over Wi-Fi.</p></details>
</fieldset></dialog>`;
