export const displayMarkup = `
<canvas id="course" tabindex="0" aria-label="Golf course. Drag to explore, scroll to zoom, double click to reframe."></canvas>
<section id="portal" aria-label="Purity clubhouse">
 <header class="site-header"><a class="brand" href="#home" aria-label="Purity home">purity<span>↗</span></a><nav aria-label="Main navigation"><a href="#home" data-route-link="home">Home</a><a href="#course" data-route-link="course">The course</a><a href="#guide" data-route-link="guide">How to play</a></nav><a href="#play" class="header-play" data-open-controls>Enter the course ↗</a></header>
 <main>
  <section class="portal-page home-page" data-page="home"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> A NEW WAY TO PLAY</p><h1>A wider view.<br>A closer <em>feel.</em></h1><p class="hero-description">The course in front of you.<br>The next move in your hands.</p><div class="hero-actions"><a href="#play" class="primary" data-open-controls>Play on this screen <span>↗</span></a><a href="#pair" class="quiet-link">Connect a phone <span>↗</span></a></div><p class="hero-note">No account. No downloads. Just a little room to play.</p></div><div class="scene-label"><span class="label-line"></span><span>01 / CREEK & SHOULDER<small>YOUR FIRST FAIRWAY</small></span></div><div class="home-bottom"><a class="feature-link" href="#course"><span class="feature-number">01</span><div><small>THE PRACTICE COLLECTION</small><h2>Meet Creek & Shoulder</h2><p>A winding creek. A raised green. Your line through it.</p></div><span class="round-arrow">↗</span></a><a class="story-link" href="#story"><span class="eyebrow">A DIFFERENT PERSPECTIVE</span><h2>One game.<br>Two ways to be there. ↗</h2></a></div></section>
  <section class="portal-page course-page" data-page="course" hidden><a class="back-link" href="#home">← Home</a><p class="eyebrow">THE PRACTICE COLLECTION / 01</p><h1>Read the land.<br>Find your line.</h1><div class="course-selection"><div class="course-art" aria-hidden="true"><svg viewBox="0 0 560 270"><path fill="#3e6747" d="M-30 170Q80 20 210 70T610 15V300H-30Z"/><path fill="#6f9458" d="M25 215Q80 195 160 158T275 138 358 80 518 65Q537 88 500 112T355 134 260 185 70 241Z"/><path fill="#a7bc76" d="M45 216Q111 211 164 178T277 159 365 103 505 79Q524 90 491 100T353 119 265 172 61 234Z"/><path fill="none" stroke="#78a8a0" stroke-width="20" d="M130 300Q160 216 235 200T321 170 350 135 425 145 489 67 560 20"/><path fill="#d9d5a8" d="M390 70q40-22 41-4t-45 21q-13-7 4-17"/><ellipse fill="#b9cc89" cx="499" cy="84" rx="24" ry="14"/><path stroke="#edf1d6" stroke-width="3" d="M499 84V49"/><path fill="#dc906a" d="M500 49l20 7-20 7"/><circle fill="#f2f4e7" cx="61" cy="222" r="5"/></svg><span>ILLUSTRATED COURSE STUDY</span></div><div class="course-details"><div class="pill">AVAILABLE TO PLAY</div><h2>Creek & Shoulder</h2><p>Work your way up a narrow fairway, negotiate the creek, and land softly on the raised green.</p><dl><div><dt>Format</dt><dd>Single-hole practice</dd></div><div><dt>Your choice</dt><dd>3 tees · 3 pin positions</dd></div><div><dt>Conditions</dt><dd>Adjustable wind & ground</dd></div></dl><div class="hero-actions"><a class="primary" href="#play" data-open-controls>Play this course ↗</a><a class="quiet-link" href="#pair">Use my phone ↗</a></div></div></div><p class="page-footnote">One playable hole in this collection. New conditions give you a different challenge.</p></section>
  <section class="portal-page guide-page" data-page="guide" hidden><a class="back-link" href="#home">← Home</a><p class="eyebrow">FIND YOUR RHYTHM</p><h1>Less figuring out.<br>More <em>playing.</em></h1><div class="guide-cards"><article><span class="guide-number">01</span><h2>Choose your seat.</h2><p>Open the controls over the course, or scan the QR on a phone connected to the same Wi-Fi. Switch whenever you like.</p><a href="#pair">Connect a phone ↗</a></article><article><span class="guide-number">02</span><h2>Make your decision.</h2><p>Drag the aim pad, choose a club from My bag and set your effort. Shape & flight gives you the finer adjustments.</p><a href="#play" data-open-controls>Try the controls ↗</a></article><article><span class="guide-number">03</span><h2>Let the course respond.</h2><p>Play your shot and follow the ball. Then continue from its lie, or take a mulligan and try another approach.</p><a href="#course">Explore the course ↗</a></article></div><div class="guide-footer"><span>LOOK AROUND</span><p>Drag to pan · Scroll to zoom · Double-click to see the whole hole.<br>Use the Round tab to jump to your ball or the green.</p></div></section>
  <section class="portal-page story-page" data-page="story" hidden><a class="back-link" href="#home">← Home</a><p class="eyebrow">FROM UCG-50 TO PURITY</p><h1>A game that<br>outgrew its <em>frame.</em></h1><div class="story-columns"><p class="story-lead">It began with a whole golf simulation inside a single HTML file. The next idea was simple: give the course some space.</p><div><p>On a wide screen, the landscape gets room to breathe. On your phone, each decision sits in the palm of your hand. Playing at your desk? Bring those same controls onto the course and fold them away when you're done.</p><p>Purity is an evolving practice ground for that idea—with real simulation at its centre and a quieter, more intentional way to play around it.</p><a href="/?mode=lab" class="secondary">Visit the original UCG-50 lab ↗</a><small>The original lab is a separate experience. Opening it leaves your current practice round.</small></div></div></section>
 </main><footer class="site-footer"><span>PURITY / THE LOCAL GOLF EXPERIMENT</span><a href="#story">The story ↗</a><a href="/?mode=lab">Original lab ↗</a></footer>
</section>
<nav id="displayTools" class="display-tools" aria-label="Course navigation" hidden><a href="#home" class="brand" aria-label="Back to home">purity<span>↗</span></a><span class="course-nav-label">CREEK & SHOULDER <small>01 / PRACTICE</small></span><div><a href="#pair" id="pairButton">Connect phone ↗</a><button id="toggleControls" aria-controls="desktopControls" aria-expanded="false">Controls ⌘</button><button id="quietView" aria-label="Hide course navigation">−</button></div></nav>
<button id="revealTools" class="reveal-tools" hidden>Menu & controls ↗</button>
<section id="desktopControls" class="desktop-controls" aria-label="Desktop shot controls" hidden></section>
<dialog id="pairing" class="pairing" aria-labelledby="pairingTitle"><header><a class="back-link" href="#play">← Back to course</a><button id="closePairing" class="icon-button" aria-label="Close pairing">×</button></header><p class="eyebrow">ONE COURSE. TWO SCREENS.</p><h1 id="pairingTitle">A little space<br>between you &<br><em>the controls.</em></h1><p>Scan with your phone. Keep both devices on the same Wi-Fi.</p><canvas id="qr" aria-label="Pairing QR code"></canvas><a id="cockpitLink" role="button">Copy phone pairing link ↗</a><input id="pairUrl" aria-label="Phone pairing link" readonly hidden><label id="networkLabel" hidden>Wi-Fi address<select id="network"></select></label><p id="pairStatus" role="status">Preparing your connection…</p><button id="playHere" class="secondary">Use controls on this screen instead</button></dialog>`;
